# Generated by Django 5.2.15 on 2026-06-04 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['external_id'], name='conversatio_externa_d50d8e_idx'), models.Index(fields=['display_name'], name='conversatio_display_74a632_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_since', models.DateTimeField(blank=True, null=True)),
                ('last_fan_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_chatter_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_chatter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('model_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='model_accounts.modelaccount')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='conversations.fan')),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('FAN', 'Fan'), ('CHATTER', 'Chatter'), ('SYSTEM', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('PPV', 'PPV')], default='TEXT', max_length=20)),
                ('text', models.TextField()),
                ('ppv_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_message_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConversationReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_read_states', to=settings.AUTH_USER_MODEL)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.message')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.message'),
        ),
        migrations.CreateModel(
            name='ResponseTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('response_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ANSWERED', 'Answered')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_timers', to='conversations.conversation')),
                ('started_by_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_response_timers', to='conversations.message')),
                ('stopped_by_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_response_timers', to='conversations.message')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='conversatio_convers_ca4693_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type', 'created_at'], name='conversatio_sender__c61e04_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_message_id'], name='conversatio_client__b7dddb_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('conversation', 'client_message_id'), name='unique_client_message_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['user', 'unread_count'], name='conversatio_user_id_c3d8be_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationreadstate',
            index=models.Index(fields=['conversation', 'user'], name='conversatio_convers_764139_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationreadstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_read_state_per_conversation_user'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_chatter', 'status'], name='conversatio_assigne_c08de5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'waiting_since'], name='conversatio_status_60dff8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['model_account', 'status'], name='conversatio_model_a_598056_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['fan'], name='conversatio_fan_id_14bee9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='conversatio_last_me_94938f_idx'),
        ),
        migrations.AddIndex(
            model_name='responsetimer',
            index=models.Index(fields=['conversation', 'status'], name='conversatio_convers_8dbea7_idx'),
        ),
        migrations.AddIndex(
            model_name='responsetimer',
            index=models.Index(fields=['status', 'started_at'], name='conversatio_status_4d8f67_idx'),
        ),
        migrations.AddIndex(
            model_name='responsetimer',
            index=models.Index(fields=['started_at'], name='conversatio_started_bfa124_idx'),
        ),
    ]
