# Generated by Django 5.2.15 on 2026-06-04 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_last_seen_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('CHATTER', 'Chatter'), ('TEAMLEAD', 'Teamlead'), ('ADMIN', 'Admin')], default='CHATTER', max_length=20)),
                ('is_revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='accounts_us_token_508a2b_idx'), models.Index(fields=['role'], name='accounts_us_role_31057c_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_706e25_idx'), models.Index(fields=['is_revoked'], name='accounts_us_is_revo_620f09_idx'), models.Index(fields=['accepted_at'], name='accounts_us_accepte_d130bf_idx')],
            },
        ),
    ]
